DROP TABLE ARK_DEMO_ORDER;
DROP TABLE ARK_DEMO_NEW_ORDER;
DROP TABLE ARK_DEMO_CHK;
DROP TABLE CLIENT_NAME;
DROP SEQUENCE ARK_DEMO_SEQ;
CREATE SEQUENCE ARK_DEMO_SEQ;
 
CREATE TABLE CLIENT_NAME
(ID    NUMBER PRIMARY KEY,
NAME VARCHAR2(20));
 
Insert into CLIENT_NAME (ID,NAME) values (1,'SMITH');
Insert into CLIENT_NAME (ID,NAME) values (2,'ALLEN');
Insert into CLIENT_NAME (ID,NAME) values (3,'WARD');
Insert into CLIENT_NAME (ID,NAME) values (4,'JONES');
Insert into CLIENT_NAME (ID,NAME) values (5,'MARTIN');
Insert into CLIENT_NAME (ID,NAME) values (6,'BLAKE');
Insert into CLIENT_NAME (ID,NAME) values (7,'CLARK');
Insert into CLIENT_NAME (ID,NAME) values (8,'SCOTT');
Insert into CLIENT_NAME (ID,NAME) values (9,'KING');
Insert into CLIENT_NAME (ID,NAME) values (10,'TURNER');
Insert into CLIENT_NAME (ID,NAME) values (11,'ADAMS');
Insert into CLIENT_NAME (ID,NAME) values (12,'JAMES');
Insert into CLIENT_NAME (ID,NAME) values (13,'FORD');
Insert into CLIENT_NAME (ID,NAME) values (14,'MILLER');
 
CREATE TABLE ARK_DEMO_ORDER
(
ID    NUMBER,
ROW_CD   CHAR(1),
CLN_NM    VARCHAR2(20),
ORD_DT    DATE,
SUM_PRC    NUMBER,
DEP_ACC    VARCHAR2(20),
INV_ID    NUMBER,
DV_ADDR    VARCHAR2(500),
DV_DT    VARCHAR2(8),   -- YYYYMMDD
PKG_NO NUMBER,
PKG_NAME VARCHAR2(20),
PKG_STR1 VARCHAR2(50),
PKG_STR2 VARCHAR2(50),
PKG_STR3 VARCHAR2(50),
PKG_STR4 VARCHAR2(50),
PKG_STR5 VARCHAR2(50),
PKG_STR6 VARCHAR2(50),
PKG_STR7 VARCHAR2(50),
PKG_STR8 VARCHAR2(1000),
PKG_STR9 VARCHAR2(4000),
ORD_TIME   TIMESTAMP,
UPD_YN      CHAR(1) DEFAULT 'N',
UPD_TIME   TIMESTAMP,
constraint ARK_DEMO_ORDER_PK PRIMARY KEY(ID, ROW_CD)
);
 
CREATE TABLE ARK_DEMO_NEW_ORDER
(
ID    NUMBER PRIMARY KEY,
CLN_NM    VARCHAR2(20),
ORD_DT    DATE,
SUM_PRC    NUMBER,
DEP_ACC    VARCHAR2(20),
INV_ID    NUMBER,
DV_ADDR    VARCHAR2(500),
DV_DT    VARCHAR2(8),   -- YYYYMMDD
PKG_NO NUMBER,
PKG_NAME VARCHAR2(20),
PKG_STR1 VARCHAR2(50),
PKG_STR2 VARCHAR2(50),
PKG_STR3 VARCHAR2(50),
PKG_STR4 VARCHAR2(50),
PKG_STR5 VARCHAR2(50),
PKG_STR6 VARCHAR2(50),
PKG_STR7 VARCHAR2(50),
PKG_STR8 VARCHAR2(1000),
PKG_STR9 VARCHAR2(4000),
ORD_TIME   TIMESTAMP
);
 
CREATE TABLE ARK_DEMO_CHK
(
ID    NUMBER PRIMARY KEY,
SLD_LST  VARCHAR2(50),
STG_LST  VARCHAR2(50),
DSC_LST  VARCHAR2(50),
CHK_DT    VARCHAR2(8),  -- YYYYMMDD
PKG_NO NUMBER,
CHK_TIME TIMESTAMP,
UPD_YN      CHAR(1) DEFAULT 'N',
UPD_TIME   TIMESTAMP
);
